name: harvestechcorp
favicon: null
layout_spectrum: 0.75667
typography_spectrum: 1
title: HarvesTech Corp.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#91a3af'
    - '#e5dace'
    - '#a77f2e'
    - '#346d9c'
    - '#470600'
  brandStrength: 0.814955010311678
  lightness: 0.5903496900573373
  saturation: 0.18584088329225779
  rhythmicContrast: 0.7997816789429635
purpose: []
